name: Continuous Deployment to Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ssh_key
        chmod 700 ~/.ssh/ssh_key
    - name: SSH into vm
      run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh_key ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}
    - run: ls
    - name: Pull latest code
      run: ls && cd sketchpencil && git pull origin main
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm run build
    - name: Restart servers
      run: |  
        pm2 restart frontend
        pm2 restart http-backend
        pm2 restart ws-backend
